name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      PT_BASE_URL: https://api.practitest.com
      PT_PROJECT_ID: ${{ secrets.PT_PROJECT_ID }}
      PT_SET_ID: ${{ secrets.PT_SET_ID }}
      PT_EMAIL: ${{ secrets.PT_EMAIL }}
      PT_TOKEN: ${{ secrets.PT_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npm test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
